config/routes.rb
Rails.application.routes.draw do
  get '/health', to: 'application#health'

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  devise_for :admin, except: [:new]
  
  devise_for :users

  root to: 'clients#index'

  resources :tributes
  resources :companies
  resources :settings

  resources :revenues
  resources :revenues

  get "revenue/:id/start" => 'revenues#start', :as => :revenues_start
  
  resources :clients, only: [:index, :create, :edit, :show]
  get "client/:id/add_store" => 'clients#add_store', :as => :client_add_store
  get "client/:id/add_channel_store" => 'clients#add_channel_store', :as => :client_add_channel_store
  get "client/:id/add_table_tax" => 'clients#add_table_tax', :as => :client_add_table_tax
  get "client/:id/add_contact" => 'clients#add_contact', :as => :client_add_contact
  get "client/:id/remove_store/:store_id" => 'clients#remove_store', :as => :client_remove_store
  get "client/:id/remove_channel_store/:channel_id" => 'clients#remove_channel_store', :as => :client_remove_channel_store
  get "client/:id/remove_table_tax/:table_tax_id" => 'clients#remove_table_tax', :as => :client_remove_table_tax
  get "client/:id/remove_contact/:contact_id" => 'clients#remove_contact', :as => :client_remove_contact

  get "client/:id/stores" => 'clients#stores', :as => :client_stores
  get "client/:id/channel_stores" => 'clients#channel_stores', :as => :client_channel_stores
  get "client/:id/table_taxes" => 'clients#table_taxes', :as => :client_table_taxes

  resources :pendencies, except: [:show]
  get "pendencies/clients" => 'pendencies#clients', :as => :pendencies_client

  resources :client_steps

  resources :cnpjs, :only => ['new', 'create']
  get "cnpjs/new_cnpj" => 'cnpjs#new_cnpj', :as => :new_cnpj_modal
  get "cnpjs/edit_cnpj/:id" => 'cnpjs#edit_cnpj', :as => :edit_cnpj_modal
  get "cnpjs/edit_cnpj_partial/:id" => 'cnpjs#edit_cnpj_partial', :as => :edit_cnpj_partial

  resources :stores, :only => ['new', 'create', 'edit']

  resources :channel_stores, :only => ['new', 'create']

  resources :table_taxes, :only => ['new', 'create']
  get "table_taxes/new_table_tax" => 'table_taxes#new_table_tax', :as => :new_table_tax_modal
  get "table_taxes/clone_table_tax/:id" => 'table_taxes#clone_table_tax', :as => :clone_table_tax
  get "table_taxes/show_table_tax/:id" => 'table_taxes#show_table_tax', :as => :show_table_tax
  post "table_taxes/create_row" => 'table_taxes#create_row', :as => :create_row
  post "table_taxes/remove_row" => 'table_taxes#remove_row', :as => :remove_row  
  post "table_taxes/create_rule" => 'table_taxes#create_rule', :as => :create_rule
  post "table_taxes/remove_rule" => 'table_taxes#remove_rule', :as => :remove_rule
  post "table_taxes/remove_unsaved_instance" => 'table_taxes#remove_unsaved_instance', :as => :remove_unsaved_instance
end

app/models/channel_store.rb
class ChannelStore < ApplicationRecord
  belongs_to :cnpj
  belongs_to :store
  belongs_to :marketplace
  belongs_to :client
  belongs_to :table_tax

  has_and_belongs_to_many :bank_slips

  validates :client_id, :cnpj_id, :store_id, :marketplace_id, :table_tax_id, :monthly_payment, :order_payment, :payday, :additional_time_day, :additional_time_day_based, :presence => true, :if => :active?

  def active?
  	self.status == 'active'
  end

  def draft?
    self.status == 'draft'
  end

  def valid_fields?
  	old_status = self.status
  	self.status = 'active'

  	valid_fields = self.valid? && cnpj_valid? && !duplicate_name?

  	self.status = old_status
  	valid_fields
  end

  def cnpj_valid?
    old_status = self.status
    self.status = 'active'
    
    valid_cnpj = self.cnpj.valid?
    self.status = old_status
    
    valid_cnpj
  end

  def duplicate_name?
    other_channels.detect{|c| c.name == self.name }.present?
  end

  def other_channels
    self.client.channel_stores.select{|c| c.active? && c.id != self.id}
  end

  def name
    "#{self.store.name} - #{self.marketplace.name}" if self.store && self.marketplace
  end

  def self.fallback_client_params channel_hash, client
    channel_hash.merge!({:payday => client.payday,
                    :additional_time_day => client.additional_time_day,
                    :additional_time_day_based => client.additional_time_day_based
                   })
    channel_hash.merge!({:cnpj_id => client.cnpj.id}) if client.cnpj
    channel_hash
  end

  def has_bank_slip? revenue
    bank_slips.detect{|bs| bs.revenue.id == revenue.id}.present?
  end

  def additional_time_unabbreviated
    if self.additional_time_day > 1
      dia = 'dias'
      additional_time_day_based = self.additional_time_day_based.mb_chars.downcase.to_s
    else
      dia = 'dia'
      additional_time_day_based = 'corrido' if self.additional_time_day_based == 'Corridos'
      additional_time_day_based = 'útil' if self.additional_time_day_based == 'Úteis'
    end

    "#{self.additional_time_day} #{dia} #{additional_time_day_based}"
  end

  def date_payment
    (Date.current.beginning_of_month + 1.month).change(day: self.payday)
  end

  def additional_time_working_days?
    self.additional_time_day_based.parameterize == 'util'
  end

  def additional_time_date
    return date_payment if self.additional_time_day == 0

    add_time_day = self.additional_time_day
    @add_time_date = date_payment.dup

    loop do
      @add_time_date += 1.day
      add_time_day -= 1 if consider_date?(@add_time_date)
      break if add_time_day == 0
    end

    @add_time_date
  end

  def consider_date? date
    return true unless additional_time_working_days?
    working_days?(date)
  end

  def self.working_days? date
    (1..5).include?(date.wday)
  end
end

app/controllers/channel_stores_controller.rb
class ChannelStoresController < ApplicationController
end

app/helpers/channel_stores_helper.rb
module ChannelStoresHelper

	def list_store channel_store
		store_list = Store.where({client_id: channel_store.client_id, :status => 'active'})

		store_list.map do |store| 
			[store.name, store.id]
		end
	end

  	def store_prompt_text list_stores
		list_stores.blank? ? 'Nenhuma loja conectada' : '-- Selecione --'
	end

	def list_marketplace
		@list_marketplace ||= Marketplace.all.map{|mkp| [mkp.name, mkp.id] }
	end
end

app/views/channel_stores/_channel_table_tax.html.erb
<% content_for(:page_modal, flush: true) do %>
  <div id="modal-table-tax" class="modal fade" role="dialog" aria-labelledby="TableTax" aria-hidden="true"></div>
<% end %>

<h4>TABELA DE TRIBUTOS</h4>
<hr>
<%= fields_for 'table_taxes[]', table_tax do |table_tax_fields| %>
<%= table_tax_fields.hidden_field :id %>
<div class="row form-group">
  <div class="col-md-6">
    <%= table_tax_fields.label :channels do %>
      Canais <i class="fa fa-question-circle" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Selecione um ou mais canais"></i>
    <% end %>
    <p class="help-block">Para selecionar multiplos canais segure a tecla <span class="badge">CTRL</span> </br>e selecione os itens desejados.</p>
    
    <%=select_tag 'channels[]', options_for_select(
                              list_channels(@client), 
                              selected_channels(@client, table_tax)
                              ), :multiple => true, class: "form-control"%>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <label for="endereco">Tabela Tribuária <i class="fa fa-question-circle" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Selecione a tabela de tributos"></i></label>
      <p class="help-block">Escolha a tabela para associar aos canais selecionados </br> anteriormente.</p>
      <div class="btn-group btn-group-justified" role="group" style="width:100%" >
        <a href="" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="width:100%">
          <%=channel_tax_selected(table_tax)%><div class="pull-right"><span class="caret"></span></div>
        </a>
        <ul id=<%="table-tax-list-#{table_tax.id}"%> class="dropdown-menu table-tax-list fade-in-0-5-s" role="menu" style="width:100%">
          <% @client_taxes_list.each do |client_table_taxe| %>
            <div style="position:relative;" class="tax-option-group" >
              <a href='' role='button' class='btn tax-option' style='width:100%' data-table-tax-id=<%=client_table_taxe.id.to_s%> ><%=client_table_taxe.name %>
                
              </a>
              <%= link_to '', client_remove_table_tax_path({:id=> client_table_taxe.client.id,:table_tax_id => client_table_taxe.id }), :class => 'remove-client-table-tax glyphicon glyphicon-remove' %>
            </div>
          <% end %>
          <% @table_taxes_global.each do |table_taxe_global| %>
            <a href='' role='button' class='btn tax-global-option' style='width:100%; background:#f5f5dc;' data-table-tax-id=<%=table_taxe_global.id.to_s%> ><%=table_taxe_global.name %>
            </a>
          <% end %>
          <%= link_to new_table_tax_modal_path,  {:remote => true, 'data-toggle' => "modal", 'data-target' => "#modal-table-tax", "role" => "button", :class => "btn open-tax-modal",  "style"=>"width:100%" }  do %>
            <i class="glyphicon glyphicon-plus"></i> Adicionar Tabela Global
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="row form-group">
  <div class="col-md-12 table-tax-context">
    <%= render partial: '/table_taxes/form', :locals => { table_tax: table_tax } %>
  </div>
</div>
<% end %>

app/views/channel_stores/_form.html.erb
<% content_for(:page_modal, flush: true) do %>
  <div id="modal-cnpj" class="modal fade" role="dialog" aria-labelledby="Cnpj" aria-hidden="true"></div>
<% end %>
<hr>
<%= fields_for 'channel_stores[]', channel_store do |channel_fields| %>
  <div class="row form-group">
    <div class="col-md-6">
      <span class="label label-as-badge <%=status_label_class(channel_store)%>"><%="#{status_object(channel_store)}"%></span>
      <% if !channel_store.active? %>
        <%= link_to client_remove_channel_store_path({:id => channel_store.client.id, :channel_id => channel_store.id}), :class => "label label-danger remove-channel-store" do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row form-group">
    <div class="col-md-3 ">
      <%= channel_fields.hidden_field :cnpj_id %>
      <%= label :vat_number, "cnpj_label_id", 'NÚMERO DE INSCRIÇÃO (CNPJ)' %>
      <div class="input-group">
      <%= text_field :vat_number,  "cnpj-channel-#{channel_store.id}", class: "form-control", placeholder: "00.000.000/0000-00", :required => channel_store.active?, :data => {:mask=> '99.999.999/9999-99'}, disabled: true, value: (channel_store.cnpj.vat_number if channel_store.cnpj) %>
          <div class="input-group-addon">
            <% if channel_store.cnpj && channel_store.cnpj.vat_number.present? %>
              <%= link_to edit_cnpj_modal_path(channel_store.cnpj.id.to_s), :remote => true, 'data-toggle' => "modal", 'data-target'=>"#modal-cnpj", :class => "link-cnpj", 'data-object-id' => channel_store.id.to_s do %>
                <i class="glyphicon glyphicon-pencil transform-scale-1-5-hover transition-3-s" aria-hidden="true"></i>
              <%end%>
            <% else %>
              <%= link_to new_cnpj_modal_path, :remote => true, 'data-toggle' => "modal", 'data-target'=>"#modal-cnpj", :class => "link-cnpj", 'data-object-id' => channel_store.id.to_s do %>
                <i class="glyphicon glyphicon-pencil transform-scale-1-5-hover transition-3-s" aria-hidden="true"></i>
              <%end%>
            <% end %>
          </div>
      </div>
    </div>
  <% if channel_store.table_tax %>
    <div class="col-md-6 col-md-push-3">
      <%= label :table_tax, "tabela_tributos_id", 'TABELA DE TRIBUTOS' %>
      <div class="input-group">
      <%= text_field :table_tax,  "table-tax-#{channel_store.id}", class: "form-control", disabled: true, value: channel_store.table_tax.name %>
        <div class="input-group-addon">
          <%= link_to client_table_taxes_path(channel_store.client.id) do %>
            <i class="glyphicon glyphicon-pencil transform-scale-1-5-hover transition-3-s" aria-hidden="true"></i>
          <%end%>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="row form-group">
    <div class="col-md-4">
      <%= link_to 'Adicionar CNPJ diferente para este canal', new_cnpj_modal_path, :remote => true, 'data-toggle' => "modal", 'data-target'=>"#modal-cnpj", :class => "link-cnpj", 'data-object-id' => channel_store.id.to_s %>
    </div>
  </div>
  <div class="row form-group">
    <div class="col-md-6">
    <%= channel_fields.label :store_id, 'LOJA' %>
    <% @list_stores = list_store(channel_store) %>
    <%= channel_fields.select :store_id, @list_stores, {:prompt => store_prompt_text(@list_stores) }, class: "form-control", disabled: @list_stores.blank?, :required => channel_store.active?  %>
    </div>
    <div class="col-md-6">
    <%= channel_fields.label :marketplace_id, 'MARKETPLACE' %>
    <%= channel_fields.select :marketplace_id, list_marketplace, {:prompt => '-- Selecione --'}, class: "form-control", :required => channel_store.active? %>
    </div>
  </div>
  <div class="row form-group">
    <div class="col-md-3">
    <%= channel_fields.label :monthly_payment, 'MENSALIDADE' %>
    <%= channel_fields.number_field :monthly_payment, class: "form-control", placeholder: "0.0", min: 0, step:0.01, :value => (number_with_precision(channel_fields.object.monthly_payment, :precision => 2)), :required => channel_store.active? %>
    </div>
    <div class="col-md-3">
    <%= channel_fields.label :order_payment, 'PREÇO POR PEDIDO' %>
    <%= channel_fields.number_field :order_payment, class: "form-control", placeholder: "0.0", min: 0, :step => 0.01, :value => (number_with_precision(channel_fields.object.order_payment, :precision => 2)), :required => channel_store.active? %>
    </div>
    <div class="col-md-3">
    <%= channel_fields.label :payday, 'VENCIMENTO (dia)' %>
    <%= channel_fields.number_field :payday, class: "form-control", placeholder: "Dia de vencimento", min: 1, :required => channel_store.active?  %>
    </div>
    <div class="col-md-3">
      <%= channel_fields.label :additional_time_day, 'PRAZO ESTENDIDO (dias)' %>
      <div class="form-group dubleInput">
      <%= channel_fields.number_field :additional_time_day, class: "form-control", placeholder: "Prazo em dias"  %>
      <%= channel_fields.select :additional_time_day_based, ['Úteis', 'Corridos'], {}, class: "form-control", :required => channel_store.active? %>
      </div>
    </div>
  </div>
<% end %>