config/routes.rb
Rails.application.routes.draw do
  get '/health', to: 'application#health'

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  devise_for :admin, except: [:new]
  
  devise_for :users

  root to: 'clients#index'

  resources :tributes
  resources :companies
  resources :settings

  resources :revenues
  resources :revenues

  get "revenue/:id/start" => 'revenues#start', :as => :revenues_start
  
  resources :clients, only: [:index, :create, :edit, :show]
  get "client/:id/add_store" => 'clients#add_store', :as => :client_add_store
  get "client/:id/add_channel_store" => 'clients#add_channel_store', :as => :client_add_channel_store
  get "client/:id/add_table_tax" => 'clients#add_table_tax', :as => :client_add_table_tax
  get "client/:id/add_contact" => 'clients#add_contact', :as => :client_add_contact
  get "client/:id/remove_store/:store_id" => 'clients#remove_store', :as => :client_remove_store
  get "client/:id/remove_channel_store/:channel_id" => 'clients#remove_channel_store', :as => :client_remove_channel_store
  get "client/:id/remove_table_tax/:table_tax_id" => 'clients#remove_table_tax', :as => :client_remove_table_tax
  get "client/:id/remove_contact/:contact_id" => 'clients#remove_contact', :as => :client_remove_contact

  get "client/:id/stores" => 'clients#stores', :as => :client_stores
  get "client/:id/channel_stores" => 'clients#channel_stores', :as => :client_channel_stores
  get "client/:id/table_taxes" => 'clients#table_taxes', :as => :client_table_taxes

  resources :pendencies, except: [:show]
  get "pendencies/clients" => 'pendencies#clients', :as => :pendencies_client

  resources :client_steps

  resources :cnpjs, :only => ['new', 'create']
  get "cnpjs/new_cnpj" => 'cnpjs#new_cnpj', :as => :new_cnpj_modal
  get "cnpjs/edit_cnpj/:id" => 'cnpjs#edit_cnpj', :as => :edit_cnpj_modal
  get "cnpjs/edit_cnpj_partial/:id" => 'cnpjs#edit_cnpj_partial', :as => :edit_cnpj_partial

  resources :stores, :only => ['new', 'create', 'edit']

  resources :channel_stores, :only => ['new', 'create']

  resources :table_taxes, :only => ['new', 'create']
  get "table_taxes/new_table_tax" => 'table_taxes#new_table_tax', :as => :new_table_tax_modal
  get "table_taxes/clone_table_tax/:id" => 'table_taxes#clone_table_tax', :as => :clone_table_tax
  get "table_taxes/show_table_tax/:id" => 'table_taxes#show_table_tax', :as => :show_table_tax
  post "table_taxes/create_row" => 'table_taxes#create_row', :as => :create_row
  post "table_taxes/remove_row" => 'table_taxes#remove_row', :as => :remove_row  
  post "table_taxes/create_rule" => 'table_taxes#create_rule', :as => :create_rule
  post "table_taxes/remove_rule" => 'table_taxes#remove_rule', :as => :remove_rule
  post "table_taxes/remove_unsaved_instance" => 'table_taxes#remove_unsaved_instance', :as => :remove_unsaved_instance
end

app/models/table_tax.rb
class TableTax < ApplicationRecord
	belongs_to :client

  has_many :channel_stores
  	
	validates :name, :row_ids, :presence => true, :if => :active?
  
  def active?
    self.status == 'active'
  end

  def draft?
    self.status == 'draft'
  end

  def is_global?
    self.table_scope.upcase == 'GLOBAL'
  end

  def rows
    TableTaxRow.where({"id" => self.row_ids}).to_a
  end

  def rules
    TaxRule.where({"id" => self.tax_rule_ids}).to_a
  end

  def rows_options
    rows.map{ |row| [row.row_name, row.id] }
  end

  def valid_fields?
  	old_status = self.status
  	self.status = 'active'

  	valid_fields = self.valid?

  	self.status = old_status
  	valid_fields
  end

  def channel_linked?
    self.client && self.client.taxes_by_channels.detect{|tax| tax.id == self.id }.present?
  end

  def remove_allowed?
    (self.client && !self.channel_linked?) ||
    !self.active?
  end
end

app/controllers/table_taxes_controller.rb
class TableTaxesController < ApplicationController
  
 def index
    @table_taxes = TableTax.where({:table_scope => 'GLOBAL'}).paginate(page: params[:page], per_page: 50)

    render "index"
  end

  def new_table_tax
    @table_tax = TableTax.create({:status => 'new', :table_scope => 'GLOBAL'})

    respond_to do |format|
      format.html
      format.js
    end
  end

  def remove_unsaved_instance
    query_params = remove_table_tax_params.slice(:id).merge({:status => 'new', :table_scope => 'GLOBAL'})
    @table_tax = TableTax.find_by(query_params)

    respond_to do |format|
      if @table_tax && @table_tax.destroy
        format.json { render json: {}, :status => :ok }
      else
        format.json { render json: {}, :status => 400 }
      end
    end
  end

  def clone_table_tax
    @table_tax = TableTax.find(params[:id])
    table_tax_params = @table_tax.attributes.except('table_scope', 'id').merge({:status => 'new'})
    @table_tax_clone = TableTax.create(table_tax_params)
    
    @table_tax_clone.tax_rule_ids = @table_tax.tax_rule_ids

    render :json => { :form => render_to_string('/table_taxes/_form', :layout => false, :locals => { :table_tax => @table_tax_clone }) }
  end

  def show_table_tax
    @table_tax = TableTax.find(params[:id])

    render :json => { :form => render_to_string('/table_taxes/_form', :layout => false, :locals => { :table_tax => @table_tax }) }
  end

  def create
    @table_tax = TableTax.find(table_tax_params[:id])
    @table_tax.name = table_tax_params[:name]
    @table_tax.status = 'active'

    respond_to do |format|
      if valid_required_fields?(@table_tax) && @table_tax.save
        format.json { render json: {}, :status => :ok }
      else
        puts @table_tax.errors.join('') if valid_required_fields?(@table_tax)
        puts 'Erro no preenchimento dos campos' unless valid_required_fields?(@table_tax)
        format.json { render json: {}, :status => 400 }
      end
    end
  end
  
  def valid_required_fields? table_tax
    table_tax.name.present? && table_tax.row_ids.present?
  end

  def create_row
    @table_tax_row = TableTaxRow.where(row_params.except(:id)).first_or_initialize
    @table_tax = TableTax.find(table_params["id"])

    respond_to do |format|
      if @table_tax_row.save && !@table_tax.row_ids.include?(@table_tax_row.id)
        set_row_in_table(@table_tax_row, @table_tax)

        format.json { render :partial => "table_taxes/table_tax_row_line.html.erb", :locals => {row: @table_tax_row}, :format => [:html], :status => :ok, :layout => false }
      elsif @table_tax.row_ids.include?(@table_tax_row.id)
        format.json { render json: {:row_id => @table_tax_row.id.to_s}, :status => 409 }
      elsif @table_tax_row.errors.full_messages.present?
        format.json { render json: @table_tax_row.errors.full_messages.join("; "), :status => 422 }
      else
        format.json { render json: "Erro Interno. Entre com contato com nosso suporte.", :status => 400 }
      end
    end
  end

  def remove_row
    @table_tax = TableTax.find(table_params["id"])
    @table_tax_row = TableTaxRow.find(row_params["id"])

    respond_to do |format|
      if delete_row_in_table(@table_tax_row, @table_tax)
        format.json { render json: "Registro removido com sucesso", :status => :ok }
      else
        format.json { render json: @table_tax.errors.full_messages.join("; "), :status => 400 }
      end
    end
  end

  def create_rule
    @table_tax = TableTax.find(table_params["id"])

    row_ids_params = sort_rule_ids(rule_params['row_ids'])
    query_array = TaxRule.where(row_ids_array_query, row_ids_params)
    @table_tax_rule = query_array.where(rule_params.slice(:operator, :measurement, :value)).first_or_initialize    
    @table_tax_rule.row_ids = row_ids_params if @table_tax_rule.id.blank?

    respond_to do |format|
      if @table_tax_rule.save && !@table_tax.row_ids.include?(@table_tax_rule.id)
        set_rule_in_table(@table_tax_rule, @table_tax)

        format.json { render :partial => "table_taxes/table_tax_rule_line.html.erb", :locals => {rule: @table_tax_rule}, :format => [:html], :status => :ok, :layout => false }
      elsif @table_tax.row_ids.include?(@table_tax_rule.id)
        format.json { render json: {:row_id => @table_tax_rule.id.to_s}, :status => 409 }
      elsif @table_tax_rule.errors.full_messages.present?
        format.json { render json: @table_tax_rule.errors.full_messages.join("; "), :status => 422 }
      else
        format.json { render json: "Erro Interno. Entre com contato com nosso suporte.", :status => 400 }
      end
    end
  end

  def row_ids_array_query
    "row_ids = ARRAY[?]::integer[]"
  end

  def remove_rule
    @table_tax = TableTax.find(table_params["id"])
    @table_tax_rule = TaxRule.find(rule_params["id"])

    respond_to do |format|
      if delete_rule_in_table(@table_tax_rule, @table_tax)
        format.json { render json: "Registro removido com sucesso", :status => :ok }
      else
        format.json { render json: @table_tax.errors.full_messages.join("; "), :status => 400 }
      end
    end
  end

private
  def table_tax_params
    params.require(:table_tax).permit(:id, :name)
  end

  def remove_table_tax_params
    params.require(:table_tax).permit(:id)
  end

  def row_params
    params.require(:rows).permit(:id, :row_type, :row_name, :row_measurement, :row_value)
  end

  def rule_params
    params.require(:rules).permit([:id, {:row_ids => []}, :operator, :measurement, :value])
  end

  def table_params
    params.require(:table).permit(:id)
  end

  def set_row_in_table row, table
    table.row_ids << row.id
    table.save
  end

  def delete_row_in_table row, table
    table.row_ids = table.row_ids.reject{|r| r == row.id}
    table.save
  end

  def set_rule_in_table rule, table
    table.tax_rule_ids << rule.id
    table.tax_rule_ids = sort_rule_ids(table.tax_rule_ids)
    table.save
  end

  def sort_rule_ids tax_rules_ids
    tax_rules_ids.sort_by{ |id_rule| id_rule }    
  end

  def delete_rule_in_table rule, table
    table.tax_rule_ids = table.tax_rule_ids.reject{|r| r == rule.id}
    table.save
  end
end

app/helpers/table_taxes_helper.rb
module TableTaxesHelper
end

app/views/table_taxes/_form.html.erb
<div class="table-tax-alert" style="display:none" ></div>
<div class="row form-group form-table-tax">
  <div class="col-md-12">
    <div class="form-group">
    <%= fields_for table_tax do |f| %>
      <%= f.hidden_field :id, 'data-table-id' => table_tax.id, :class => 'table-tax-id' %>

      <% table_tax.row_ids.each do |row_id| %>
        <%= f.hidden_field :row_ids, :multiple => true, :value => row_id %>
      <% end %>
      
      <%= f.text_field :name, class: "form-control table-tax-name", placeholder: "Nome da tabela tributária", :required => table_tax.active? %>
      <span class="help-block"></span>
    </div>
    <table class="table">
      <thead>
        <%= render partial: '/table_taxes/table_tax_row_fields' %>
      </thead>
      <tbody class="list-tax-rows">
        <% table_tax.rows.each do |tax_row| %>
          <%= render partial: '/table_taxes/table_tax_row_line', :locals => { row: tax_row } %>
        <% end %>
      </tbody>
    </table>

    <% end %>

    <div class="row">
      <div class="col-md-12">
        <h4>Regras Condicionais</h4>
        <div class="table-tax-rules-alert" style="display:none" ></div>
        <table class="table">
            <thead class='table-tax-rule-fields'>
                <%= render partial: '/table_taxes/table_tax_rule_fields', :locals => { table_tax: table_tax } %>
            </thead>
            <tbody class="list-tax-rules">
              <% table_tax.rules.each do |tax_rule| %>
                <%= render partial: '/table_taxes/table_tax_rule_line', :locals => { rule: tax_rule } %>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/table_taxes/_new_table_tax.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title" id="table-tax-title">Cadastro de Tributos</h4>
    </div>
      <%= form_for @table_tax, :method => 'POST', :html => {:id => 'form-global-table-tax', :multipart => true,:remote => true, 'data-table-tax-id' => @table_tax.id.to_s}, url: table_taxes_path do |f| %>

        <% if @table_tax.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@table_tax.errors.count, "error") %> prohibited this table_tax from being saved:</h2>

            <ul>
            <% @table_tax.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

      <div class="modal-body">
        <%= render partial: 'form', :locals => { table_tax: @table_tax } %>
      </div>
      <div class="modal-footer">
        <%= f.submit 'Salvar', class: 'btn btn-primary' %> 
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    <% end %>
  </div>
</div>

app/views/table_taxes/_table_tax_row_fields.html.erb
<tr>
  <th>Tipo</th>
  <th>Nome</th>
  <th>Peso</th>
  <th>Valor</th>
  <th>Ações</th>
</tr>
<%= fields_for :table_tax_row do |row| %>
<tr>
  <td>
    <div class="form-group">
      <%= row.select :row_type, TableTaxRow.row_type_options, {:prompt => '-- Selecione --'}, class: "form-control input-row row-type" %>
    </div>
  </td>
  <td>
    <div class="form-group">
      <%= row.text_field :row_name, class: "form-control input-row row-name", placeholder: "Nome Tributo"%>
    </div>
  </td>
  <td>
    <div class="form-group">
      <%= row.select :row_measurement, TableTaxRow.row_measurement_options, {:prompt => '-- Selecione --'}, class: "form-control input-row row-measurement"%>
    </div>
  </td>
  <td>
    <div class="form-group">
      <%= row.number_field :row_value, class: "form-control input-row row-value", placeholder: "0.0", min: 0, :step => 0.01 %>
    </div>
  </td>
  <td>
    <%= link_to(create_row_path, class:"btn btn-primary add-table-tax-row") do %>
      <i class="fa fa-check" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>
<div class="list-tax-rows-list"></div>
<% end %>

app/views/table_taxes/_table_tax_row_line.html.erb
<tr class="table-tax-row" >
  <td>
    <%= row.row_type %>
  </td>
  <td>
    <%= row.row_name %>
  </td>
  <td>
    <%= row.row_measurement %>
  </td>
  <td>
    <%= row.row_value %>
  </td>
  <td>
    <%= link_to(remove_row_path, 'data-table-tax-row-id' => row.id.to_s, class:"btn btn-danger remove-table-tax-row") do %>
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/table_taxes/_table_tax_rule_fields.html.erb
<tr>
  <th>Registro(s)</th>
  <th>Operador Lógico</th>
  <th>Peso</th>
  <th>Valor</th>
  <th>Ações</th>
</tr>
  <%= fields_for :table_tax_rules do |row_rule| %>
  <tr>
    <td class="column-container-choise">
      <div>
        <div class="form-group">
          <%=row_rule.select :row_ids, table_tax.rows_options, {}, :multiple => true, :class => "form-control chosen-select rule-row-ids", 'data-placeholder'=>"Selecione o(s) tributo(s)" %>
        </div>
      </div>
    </td>
    <td>
      <div class="form-group">
        <%=row_rule.select :operator, TaxRule.operator_options, {}, :class => "form-control rule-operator" %>
      </div>
    </td>
    <td>
        <div class="form-group">
        <%=row_rule.select :measurement, TaxRule.measurement_options, {}, :class => "form-control rule-measurement" %>
        </div>
    </td>
    <td>
      <div class="form-group">
        <%= row_rule.number_field :value, class: "form-control input-row rule-value", placeholder: "0.0", min: 0, :step => 0.01 %>
      </div>
    </td>
    <td>
      <%= link_to(create_rule_path, class:"btn btn-primary add-table-tax-rule") do %>
        <i class="fa fa-check" aria-hidden="true"></i>
      <% end %>

    </td>
  </tr>
  <% end %>

app/views/table_taxes/_table_tax_rule_line.html.erb
<tr class="table-tax-rule" >
  <td>
    <%= rule.rows.map(&:row_name).join(' + ') %>
  </td>
  <td>
    <%= rule.operator %>
  </td>
  <td>
    <%= rule.measurement %>
  </td>
  <td>
    <%= rule.value %>
  </td>
  <td>
    <%= link_to(remove_rule_path, 'data-table-tax-rule-id' => rule.id.to_s, class:"btn btn-danger remove-table-tax-rule") do %>
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/table_taxes/new_table_tax.js.erb
$("#modal-table-tax").html("<%= escape_javascript(render 'table_taxes/new_table_tax') %>");

$(document).ready(function() {
  $('#modal-table-tax').on('show.bs.modal', function(e) {
    $('.chosen-select', this).chosen({width: "100%"});
  });

  $("#modal-table-tax").modal('show');
});

$('#modal-table-tax').on('hidden.bs.modal', function () {
   $('.table-tax-list-modal-active').removeClass('table-tax-list-modal-active');
   removeTableTax();
});

$('#form-global-table-tax').on('ajax:success', function(){
    $("#modal-table-tax").modal('hide');
    update_list_global_tables();
});

$('#form-global-table-tax').on('ajax:error', function(data){
    setAlert('danger', 'Todos os campos do registro devem estar preenchidos.');
});

var removeTableTax = function() {
  	data = { table_tax: { id: $('#modal-table-tax').find('.table-tax-id').val() } };

    $.post( '/table_taxes/remove_unsaved_instance', data );
 }

var update_list_global_tables = function() {
  $html_text = "<a href='#' role='button' class='btn tax-global-option' style='width:100%; background:#f5f5dc;' data-table-tax-id='"+$('#modal-table-tax').find('.table-tax-id').val()+"' >"+$('#modal-table-tax').find('.table-tax-name').val()+" <span class='label label-as-badge label-default'>Novo</span></a>";
  $('#content-table-taxes').find('.table-tax-list-modal-active .open-tax-modal').first().before($html_text);
  $('.table-tax-list-modal-active').removeClass('table-tax-list-modal-active');
}

var setAlert = function(type, message) {
    var alertTypeClass;
    alertTypeClass = 'alert-' + type;
    $('#modal-table-tax').find('.table-tax-alert').html("<div class='alert " + alertTypeClass + "'>" + message + "</div>");
    $('#modal-table-tax').find('.table-tax-alert').fadeOut('fast').fadeIn(400);
};