config/routes.rb
Rails.application.routes.draw do
  get '/health', to: 'application#health'

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  devise_for :admin, except: [:new]
  
  devise_for :users

  root to: 'clients#index'

  resources :tributes
  resources :companies
  resources :settings

  resources :revenues
  resources :revenues

  get "revenue/:id/start" => 'revenues#start', :as => :revenues_start
  
  resources :clients, only: [:index, :create, :edit, :show]
  get "client/:id/add_store" => 'clients#add_store', :as => :client_add_store
  get "client/:id/add_channel_store" => 'clients#add_channel_store', :as => :client_add_channel_store
  get "client/:id/add_table_tax" => 'clients#add_table_tax', :as => :client_add_table_tax
  get "client/:id/add_contact" => 'clients#add_contact', :as => :client_add_contact
  get "client/:id/remove_store/:store_id" => 'clients#remove_store', :as => :client_remove_store
  get "client/:id/remove_channel_store/:channel_id" => 'clients#remove_channel_store', :as => :client_remove_channel_store
  get "client/:id/remove_table_tax/:table_tax_id" => 'clients#remove_table_tax', :as => :client_remove_table_tax
  get "client/:id/remove_contact/:contact_id" => 'clients#remove_contact', :as => :client_remove_contact

  get "client/:id/stores" => 'clients#stores', :as => :client_stores
  get "client/:id/channel_stores" => 'clients#channel_stores', :as => :client_channel_stores
  get "client/:id/table_taxes" => 'clients#table_taxes', :as => :client_table_taxes

  resources :pendencies, except: [:show]
  get "pendencies/clients" => 'pendencies#clients', :as => :pendencies_client

  resources :client_steps

  resources :cnpjs, :only => ['new', 'create']
  get "cnpjs/new_cnpj" => 'cnpjs#new_cnpj', :as => :new_cnpj_modal
  get "cnpjs/edit_cnpj/:id" => 'cnpjs#edit_cnpj', :as => :edit_cnpj_modal
  get "cnpjs/edit_cnpj_partial/:id" => 'cnpjs#edit_cnpj_partial', :as => :edit_cnpj_partial

  resources :stores, :only => ['new', 'create', 'edit']

  resources :channel_stores, :only => ['new', 'create']

  resources :table_taxes, :only => ['new', 'create']
  get "table_taxes/new_table_tax" => 'table_taxes#new_table_tax', :as => :new_table_tax_modal
  get "table_taxes/clone_table_tax/:id" => 'table_taxes#clone_table_tax', :as => :clone_table_tax
  get "table_taxes/show_table_tax/:id" => 'table_taxes#show_table_tax', :as => :show_table_tax
  post "table_taxes/create_row" => 'table_taxes#create_row', :as => :create_row
  post "table_taxes/remove_row" => 'table_taxes#remove_row', :as => :remove_row  
  post "table_taxes/create_rule" => 'table_taxes#create_rule', :as => :create_rule
  post "table_taxes/remove_rule" => 'table_taxes#remove_rule', :as => :remove_rule
  post "table_taxes/remove_unsaved_instance" => 'table_taxes#remove_unsaved_instance', :as => :remove_unsaved_instance
end

app/models/tribute.rb
class Tribute

	def self.calc channel_store, sum_payment_base = []
		payment_base = channel_store.monthly_payment + sum_payment_base.sum
		
		channel_store.table_tax.rows.inject(payment_base) do |sum, row|
			if row.row_type == 'Provento'
				sum += measurement_calc(payment_base, row)
			elsif row.row_type == 'Desconto'
				sum -= measurement_calc(payment_base, row)
			end

			sum.round(2)
		end
	end

	def self.measurement_calc payment_base, row
		if row.row_measurement == '%'
			percent_of(payment_base, row.row_value)
		elsif row.row_measurement == 'R$'
			row.row_value 
		end
	end

	def self.percent_of base, percente
    base.to_f * (percente.to_f / 100.0)
	end
end

app/controllers/tributes_controller.rb
class TributesController < ApplicationController
  def index
    @clients = Client.where({:status =>'active'}).search(search_params).paginate(page: params[:page], per_page: 10)

    render "index"
  end

  def show
    @client = Client.find(params[:id])
  end
end

app/helpers/tributes_helper.rb
module TributesHelper

  def channel_by_tribute client, tribute
    client.channel_stores.map{|c| c if c.active? && c.table_tax_id == tribute.id}
    					 .compact.sort_by{|c| c.cnpj.vat_number }
    					 .group_by{|c| c.cnpj.vat_number }
  end
end

app/views/tributes/index.html.erb
<% content_for(:page_modal, flush: true) do %>
  <div id="modal-table-tax" class="modal fade" role="dialog" aria-labelledby="TableTax" aria-hidden="true"></div>
<% end %>

<% provide(:title, "Tributos") %>
<% provide(:page_title, "Tributos") %>

<div class="page-header">
    <h1>Tributos</h1> 
    <div class="dropdown filter">
        <%= form_tag tributes_path, :method => 'get' do %>
            <%= link_to new_table_tax_modal_path,  {:remote => true, 'data-toggle' => "modal", 'data-target' => "#modal-table-tax", "role" => "button", :class => "btn btn-primary open-tax-modal" } do %>
                Nova Tabela Global <i class="fa fa-plus-square" aria-hidden="true"></i>
            <%end%>

            <%= render partial: '/shared/search' %>
        <% end %>
    </div>
    <div class="clearfix"></div>
</div>

<div class="row fade-in-0-5-s">
    <div class="col-md-12">
        <section class="clientList">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nome Fantasia</th>
                        <th>Razão Social</th>
                        <th>CNPJ</th>
                        <th>Tabela(s) de Tributos</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                  <% @clients.each do |client| %>
                    <tr>
                        <td><%= client.cnpj.trading_name %></td>
                        <td><%= client.cnpj.company_name %></td>
                        <td><%= client.cnpj.vat_number %></td>
                        <td>
                            <% client.taxes_by_channels.each do |tax| %>
                                <%= tax.name %>
                                <br/>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to tribute_path(client.id) do%>
                            <i class="fa fa-search-plus transform-scale-1-2-hover transition-3-s" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Ver detalhes"></i>
                            <%end%>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
            <%= will_paginate @clients, renderer: BootstrapPagination::Rails %>
        </section>
    </div>
</div>

<%= "<div class='alert alert-info alert-dismissible fade in floatAlert'><button type=''button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>×</span></button><strong>Info!</strong> #{notice}</div>".html_safe if notice %>


<% content_for(:head) do %>
  <%= javascript_include_tag 'table_taxes' %>
<% end %>

app/views/tributes/show.html.erb
<% provide(:title, "Tributos | #{@client.cnpj.trading_name}") %>

<h1 class="page-header fade-in-0-5-s"><%= @client.cnpj.trading_name %>
    <small>
        <%= link_to client_table_taxes_path(@client.id) do%>
            <i class="fa fa-pencil transform-scale-1-5-hover transition-3-s" aria-hidden="true"></i>
        <%end%>
    </small>
</h1>

<div class="row fade-in-0-5-s">
    <div class="col-md-12">
        <section class="clientList">
        <% @client.taxes_by_channels.each do |tribute| %>
            <table class="table table-striped table-bordered">
                <thead>
                	<tr>
                		<h3><%=tribute.name%></h3>
                	</tr>
                    <tr>
                    	<th class="text-center"> CNPJ </th>
                        <th class="text-center"> Canais </th>
                        <th class="text-center"> Mensalidade</th>
                    <% tribute.rows.each do |row| %>
                        <th class="text-center"><%=row.row_name%> <br/>
                            <%=row.row_measurement%> <br/>
                            <%="(#{row.row_type})"%>
                        </th>
                    <% end %>
                    	<th class="text-center"> TOTAL </th>
                    </tr>
                </thead>
                <tbody>
                    <% channel_by_tribute(@client, tribute).each do |key, channel| %>
                    <tr>
                        <td class="text-center"><%=key%></td>
                        <td class="text-center">
                            <%=channel.map{|c| "#{c.name} </br>"}.join.html_safe %>
                        </td>
                        <td class="text-center">
                            <%=channel.map{|c| "#{c.monthly_payment} </br>"}.join.html_safe %>
                        </td>
                        <% tribute.rows.each do |row|%>
                            <td class="text-center"><%=row.row_value%></td>
                        <% end %>
               			<td class="text-center">
                            <% channel.map{|c| Tribute.calc(c)}.each do |total|%>
                                <%= total %>
                                <br/>
                            <% end %>
                        </td>
                    <% end %>
                    </tr>
                </tbody>
            </table>
			<br/>
        <% end %>
        </section>
    </div>
</div>